# Generated by Django 5.1.7 on 2025-03-08 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_related', to='home.product'),
        ),
    ]
